### PR TITLE
provide a /status endpoint so you can see what's going on internally

### PR DESCRIPTION
**Pull request by jmazzitelli**
the start of an endpoint that exposes what is going on internally in the agent. useful for debugging the agent configuration. We can add more things here in the future - either add more log messages (though all warning and error messages automatically go in the log) or add different parts to the status report like "metric-errors" or some such thing (right now there is a list of endpoints and whether things are OK or not per endpoint). The response comes back as yaml.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
an example of what this looks like:

`$ curl http://localhost:8081/status`

```
name: Hawkular OpenShift Agent
version: 0.2.0
commit_hash: 821e6a88e06246fb6e530372394061983dc6d612
endpoints:
  http://127.0.0.1:8081/metricsABC: Failed to obtain metric details - metric definitions
    may be incomplete. err=Failed to collect details on Prometheus metrics from [http://127.0.0.1:8081/metricsABC].
    err=Prometheus URL [http://127.0.0.1:8081/metricsABC] returned error status [404/404
    Not Found]
log:
- 'Thu, 12 Jan 2017 01:08:18 -0500: START collection: http://127.0.0.1:8081/metricsABC'
- 'Thu, 12 Jan 2017 01:08:18 -0500: WARNING: Failed to obtain metric details - metric
  definitions may be incomplete. err=Failed to collect details on Prometheus metrics
  from [http://127.0.0.1:8081/metricsABC]. err=Prometheus URL [http://127.0.0.1:8081/metricsABC]
  returned error status [404/404 Not Found]'
...
- 'Thu, 12 Jan 2017 01:08:28 -0500: WARNING: Failed to collect metrics from [http://127.0.0.1:8081/metricsABC].
  err=Failed to collect Prometheus metrics from [http://127.0.0.1:8081/metricsABC].
  err=Prometheus URL [http://127.0.0.1:8081/metricsABC] returned error status [404/404
  Not Found]'
```

**Comment by pilhuhn** [comment]
Is that also meant to be the health- and readiness probe?

**Comment by jmazzitelli** [comment]
> Is that also meant to be the health- and readiness probe?

I never thought about it, but I guess it can. I don't know what OpenShift requires of something in order to be considered a health- and readiness probe.

**Comment by pilhuhn** [comment]
On 12 Jan 2017, at 12:38, John Mazzitelli wrote:

>> Is that also meant to be the health- and readiness probe?
>
> I never thought about it, but I guess it can. I don't know what 
> OpenShift requires of something in order to be considered a health- 
> and readiness probe.

See 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#defining-a-liveness-http-request

Basically returning a code 200<=code<400 means healthy / ready
everything else is unhealthy.

Readiness = "Can I route traffic to the pod"
Health = "Do I need to kill the pod and create a new one"

**Comment by jmazzitelli** [comment]
based on that info, this endpoint is more than just a health endpoint. It would be very easy though to add a "/health" endpoint - in the agent's case, it just would always return a 200 because I don't know of any circumstances where the agent (if it can respond to the request to /health) would respond with "not ready" or "kill me".

**Comment by jmazzitelli** [comment]
oh, and also, this endpoint could be behind https with certs, so its probably not ideal to use it for this I don't think. I think we'd want a completely separate endpoint that is always unsecured http and simply returns a 200.

**Comment by jmazzitelli** [comment]
Just to document how you can access this for debugging/testing purposes from outside OS, you can use the api proxy, like this:

curl -k -H "Authorization: Bearer `oc whoami -t`" https://192.168.1.15:8443/api/v1/namespaces/openshift-infra/pods/hawkular-openshift-agent-k8hcd:8080/proxy/status

**Comment by jmazzitelli** [comment]
Here's what an example output of the /status endpoint would look like:

```
name: Hawkular OpenShift Agent
version: 0.2.0
commit_hash: e97fc4eb7296aa73f5d5f4f23c37e3063d4b1c25
pods:
  192.168.1.15/default/hawkular-openshift-agent-example-jolokia-wildfly-e3zu9/4c4359bf-d84b-11e6-af13-54ee7549ae45:
  - http://172.17.0.4:8080/BADURLjolokia-war-1.3.5
  192.168.1.15/myproject/hawkular-openshift-agent-example-prometheus-python-rq6zz/6d8fb6b7-d849-11e6-af13-54ee7549ae45:
  - http://172.17.0.2:8181/
  192.168.1.15/openshift-infra/hawkular-openshift-agent-k8hcd/c68bf5b8-d8ce-11e6-af13-54ee7549ae45:
  - http://172.17.0.3:8080/metrics
endpoints:
  http://172.17.0.2:8181/: OK
  http://172.17.0.3:8080/metrics: OK
  http://172.17.0.4:8080/BADURLjolokia-war-1.3.5: Failed to collect metrics from [http://172.17.0.4:8080/BADURLjolokia-war-1.3.5].
    err=Failed to collect metrics from Jolokia endpoint [http://172.17.0.4:8080/BADURLjolokia-war-1.3.5].
    err=Jolokia request failed. 404/404 Not Found
log:
- 'Thu, 12 Jan 2017 13:55:30 +0000: Agent Started'
- 'Thu, 12 Jan 2017 13:55:30 +0000: WARNING: Will not start collecting for endpoint
  in pod [192.168.1.15/openshift-infra/hawkular-openshift-agent-k8hcd/c68bf5b8-d8ce-11e6-af13-54ee7549ae45]
  - cannot build URL. err=Endpoint not assigned an IP address yet'
- 'Thu, 12 Jan 2017 13:55:30 +0000: START collection: http://172.17.0.4:8080/jolokia-war-1.3.5'
- 'Thu, 12 Jan 2017 13:55:30 +0000: START collection: http://172.17.0.2:8181/'
- 'Thu, 12 Jan 2017 13:55:31 +0000: START collection: http://172.17.0.3:8080/metrics'
- 'Thu, 12 Jan 2017 13:55:32 +0000: STOP collection: http://172.17.0.3:8080/metrics'
- 'Thu, 12 Jan 2017 13:55:32 +0000: START collection: http://172.17.0.3:8080/metrics'
- 'Thu, 12 Jan 2017 14:00:57 +0000: STOP collection: http://172.17.0.4:8080/jolokia-war-1.3.5'
- 'Thu, 12 Jan 2017 14:00:57 +0000: START collection: http://172.17.0.4:8080/BADURLjolokia-war-1.3.5'
- 'Thu, 12 Jan 2017 14:01:27 +0000: WARNING: Failed to collect metrics from [http://172.17.0.4:8080/BADURLjolokia-war-1.3.5].
  err=Failed to collect metrics from Jolokia endpoint [http://172.17.0.4:8080/BADURLjolokia-war-1.3.5].
  err=Jolokia request failed. 404/404 Not Found'
```

**Comment by jmazzitelli** [comment]
I just added a "health probe" endpoint to the agent. It is a simple http-only endpoint that returns a status code of 200 and response body of "OK" at the /health path. It is controlled separately from the metrics and status emitter endpoint because the thinking is we will normally always want this health probe on, even if user wants to shutdown the metrics and status endpoints (but you can also turn off the health probe too if users don't want the agent to process any incoming requests of any type).

**Comment by jmazzitelli** [comment]
@pilhuhn there is now a liveness probe defined on the agent - see latest commits in this PR.

**Comment by mwringe** [comment]
Do we want this to be public without any authentication?

**Comment by jmazzitelli** [comment]
The /status method can be put behind https - just have to give the agent its identity cert/priv key and the /status method is automatically put behind TLS/https (its the same server endpoint where the /metrics endpoint is published - see https://github.com/hawkular/hawkular-openshift-agent/blob/e27840054e0aab53980f82332079f1ee96431eec/emitter/metrics_emitter.go#L59-L81). We could add something more secure if we need to (client cert verification? we could add secret lookups to enable user/pass creds to be required)

The /health method is not behind this - its just behind unsecured http - right now it doesn't do anything other than return the two character response "OK" with a status code of 200. I wasn't sure if the k8s liveness probe was able to go over https (the examples I've seen only used http) - which is why I didn't put  it behind the /status one. But we could very easily do that.

Note also both /health and /status can be disabled by the admin deploying the agent for those that do not want to expose this. There are enabled flags in the agent config/env vars to do this - by default, they are enabled, but if we want, we can default to disabled.

The /status is mainly for debugging/testing - you will see if there are any config problems or endpoint comm problems - for example:

```
name: Hawkular OpenShift Agent
version: 0.2.0
commit_hash: 1f8cfed5fe6baf0eafa80abd90913fdddbc92b96
...
endpoints:
  myproject/hawkular-openshift-agent-example-jolokia-wildfly-fefly|http://172.17.0.3:8080/jolokia-war-1.3.5: Will
    not start collecting for endpoint in pod [192.168.1.15/myproject/hawkular-openshift-agent-example-jolokia-wildfly-fefly/6bfd43b9-d8e6-11e6-9487-54ee7549ae45]
    - cannot determine credentials. err=There is no secret named [foobar:] - credentials
    are invalid for pod [192.168.1.15/myproject/hawkular-openshift-agent-example-jolokia-wildfly-fefly/6bfd43b9-d8e6-11e6-9487-54ee7549ae45].
    err=secrets "foobar:" not found
  myproject/hawkular-openshift-agent-example-prometheus-python-hr41a|http://172.17.0.8:8181/: OK
  openshift-infra/hawkular-openshift-agent-djw2u|http://172.17.0.4:8080/metrics: OK
```

So worst case, you can disable these but if you are having problems and can't figure it out, you can redeploy the agent pod with this enabled and see what kind of problems is reports. Again, mainly for debugging and testing.

**Comment by jmazzitelli** [comment]
I added more to the endpoint statuses - not only are you told it is "OK" but you are also told how many metrics were collected in its last collection and how long it took:

```
endpoints:
  myproject/hawkular-openshift-agent-example-jolokia-wildfly-fefly|http://172.17.0.3:8080/jolokia-war-1.3.5: OK.
    Last collection gathered [3] metrics in [1.689207ms]
  myproject/hawkular-openshift-agent-example-prometheus-python-vfcdx|http://172.17.0.8:8181/: OK.
    Last collection gathered [6] metrics in [1.035337ms]
  openshift-infra/hawkular-openshift-agent-fby9p|http://172.17.0.4:8080/metrics: OK.
    Last collection gathered [22] metrics in [2.157138ms]
```

**Comment by jmazzitelli** [comment]
looks like liveness probes can use https - we should probably support that, too. I guess it means I can just piggy back on the emitter endpoint rather than have two http servers.

**Comment by jmazzitelli** [comment]
OK, I think this is ready. I refactored it a bit. You can enable/disable whatever you don't want (there are three - /metrics, /status, /health). /metrics is obviously the metrics that agent can use to monitor itself. /status is this debugging tool that gives some really good info that helps you know if the agent is collecting things OK and if there are comm or config issues. /health is the health liveliness probe. If you disable all three, the server endpoint isn't even started (so the agent doesn't listen to its port). If you give the agent an identity, this endpoint automatically goes secure behind https.

**Comment by mwringe** [comment]
LGTM

**Pull request merged**
