### PR TITLE
issue #93 - use go duration strings for collection interval and minimum interval

### PR DESCRIPTION
**Pull request by jmazzitelli**
the collection intervals and minimum collection interval is now specified as strings in the form of Go durations (e.g. "1m" , "30s") etc.

### CODE REVIEW

**Comment by jmazzitelli** [comment]
this is ready to merge when we are ready. The agent config now has "minimum_collection_interval" and all endpoints now have collection_interval (the old _Secs versions of those settings have been removed).

Both are strings to be specified in go duration format such as "5m" or "30s" or even "1m30s".

**Comment by mwringe** [comment]
Awesome

**Comment by jmazzitelli** [comment]
I'm going to add something to this before merging. Right now if an endpoint does not indicate a collection interval, it takes a hardcoded default of 5m. I would like to have a "default_collection_interval" that the admin can set in the agent config so he can determine what the endpoints' default intervals will be if not specified. this why they can be able to tell the agent "all endpoints on this node will have their metrics collected every 1m" or whatever they want. If the admin doesn't set the default collection interval THEN I will set it to some hardcoded value (like "5m").

**Comment by mwringe** [comment]
If no interval is specified, I would think we should just use the minimal interval.

I assume most people are not even going to be setting a collection interval at all, and just rely on the default minimum (eg they want metrics gathered at whatever rate they are able to)

**Comment by jmazzitelli** [comment]
The minimum interval is going to be really small though - it is meant to avoid a configmap author from trying to collect things super fast ("1ms"). The minimum is the lowest any interval is possibly allowed to avoid something doing something by mistake or mallicious and trying to cause the agent to "overheat" trying to collect things super fast like every 1 millisecond. The default for this minimum is currently 5 seconds.

I don't think we want the default to be anything close to the lowest possible minimum value. We'll want a default to be something like "30s"  or maybe even "1m".  If we, by default, set endpoints to be collecting the minimum interval of every 5s, that's going to cause a huge amount of traffic and load both on the agent and the server-side h-metrics.

**Pull request merged**
